<a href="https://colab.research.google.com/github/lawakobadu/Kelompok-1-APM/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('winequality-red.csv')
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [67]:
x = data[['pH']]
y = data['quality']

In [69]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 100)

In [70]:
model = LinearRegression()  
model.fit(x_train, y_train)

LinearRegression()

In [72]:
print("Intercept: ", model.intercept_)
print("Coefficients:")
list(zip(x, model.coef_))

Intercept:  6.6286785342825665
Coefficients:

[('pH', -0.29853130616569684)]

In [73]:
#Prediction of test set
y_pred_model= model.predict(x_test)
#Predicted values
print("Prediction for test set: {}".format(y_pred_model))

Prediction for test set: [5.61367209 5.64651054 5.55098052 5.57486302 5.55993646 5.64352522
 5.68531961 5.65845179 5.66442242 5.62561335 5.64352522 5.59874553
 5.69129023 5.59576021 5.61964272 5.64949585 5.65248116 5.62561335
 5.64949585 5.67039304 5.56590708 5.59874553 5.62561335 5.56590708
 5.6375546  5.65546648 5.69129023 5.57784834 5.63456928 5.62262803
 5.62859866 5.64053991 5.65546648 5.56292177 5.61367209 5.64651054
 5.65546648 5.61665741 5.60471615 5.67337835 5.63456928 5.61964272
 5.64053991 5.64053991 5.69726086 5.72114336 5.61665741 5.65546648
 5.68531961 5.59874553 5.66442242 5.63456928 5.55396583 5.57187771
 5.69129023 5.69129023 5.67934898 5.60471615 5.68830492 5.65546648
 5.6375546  5.59874553 5.64352522 5.65546648 5.61367209 5.62859866
 5.67039304 5.56292177 5.68830492 5.7062168  5.6375546  5.51814208
 5.66740773 5.65546648 5.68531961 5.62262803 5.61665741 5.60770147
 5.65546648 5.62859866 5.63456928 5.57784834 5.72711399 5.64053991
 5.56292177 5.55993646 5.64949585 5.62262803 5.5927749  5.64949585
 5.69726086 5.65546648 5.59874553 5.66442242 5.69129023 5.62859866
 5.61068678 5.69726086 5.6375546  5.64949585 5.64949585 5.66740773
 5.58381896 5.66442242 5.58083365 5.64949585 5.65248116 5.68531961
 5.56590708 5.62561335 5.63158397 5.55396583 5.69726086 5.70323149
 5.66442242 5.55396583 5.63158397 5.71517274 5.64053991 5.62262803
 5.68531961 5.6375546  5.61665741 5.65845179 5.61665741 5.59576021
 5.57784834 5.53008333 5.72412868 5.65546648 5.62859866 5.61665741
 5.64651054 5.65546648 5.62859866 5.64053991 5.6375546  5.64352522
 5.70920211 5.64352522 5.65546648 5.70323149 5.72711399 5.68830492
 5.64053991 5.62859866 5.61665741 5.5927749  5.64053991 5.64651054
 5.69427555 5.70323149 5.46440644 5.6375546  5.57784834 5.60770147
 5.6375546  5.5688924  5.62561335 5.67934898 5.60173084 5.62262803
 5.69129023 5.65248116 5.63158397 5.6375546  5.67039304 5.59576021
 5.64053991 5.59874553 5.7062168  5.63456928 5.67337835 5.59874553
 5.70323149 5.5927749  5.58381896 5.63158397 5.62561335 5.64651054
 5.73308462 5.65248116 5.68233429 5.52709801 5.68531961 5.63456928
 5.57187771 5.62859866 5.64651054 5.6375546  5.67636367 5.61964272
 5.62859866 5.64949585 5.71517274 5.64651054 5.63456928 5.66442242
 5.64651054 5.59576021 5.57784834 5.68830492 5.61964272 5.66740773
 5.61068678 5.63158397 5.66442242 5.60173084 5.65546648 5.75099649
 5.64949585 5.64949585 5.59576021 5.62262803 5.64352522 5.63158397
 5.65845179 5.5927749  5.53306864 5.64053991 5.62859866 5.59576021
 5.58381896 5.6614371  5.65546648 5.64651054 5.60173084 5.61367209
 5.6375546  5.63456928 5.59576021 5.70323149 5.59576021 5.58978959
 5.58978959 5.5688924  5.63158397 5.68531961 5.69726086 5.62561335
 5.64949585 5.64651054 5.5927749  5.62561335 5.59874553 5.62262803
 5.65845179 5.64352522 5.64651054 5.67934898 5.67039304 5.61068678
 5.53008333 5.5927749  5.60770147 5.62262803 5.57187771 5.56292177
 5.65546648 5.69726086 5.67934898 5.63456928 5.64053991 5.61068678
 5.63456928 5.67636367 5.67337835 5.59874553 5.71218742 5.64651054
 5.67337835 5.67934898 5.61665741 5.62561335 5.66740773 5.67337835
 5.67337835 5.60173084 5.58083365 5.61068678 5.61665741 5.64352522
 5.69129023 5.67039304 5.61367209 5.64352522 5.73308462 5.57784834
 5.64651054 5.65546648 5.58381896 5.64352522 5.55098052 5.46440644
 5.57187771 5.63158397 5.55993646 5.61068678 5.66740773 5.62859866
 5.63158397 5.68233429 5.6375546  5.68830492 5.61964272 5.64053991
 5.65845179 5.66740773 5.69129023 5.64651054 5.67039304 5.55695115
 5.65248116 5.60770147 5.67337835 5.61068678 5.57486302 5.67636367
 5.64949585 5.65546648 5.67039304 5.67337835 5.65845179 5.56292177
 5.65546648 5.62561335 5.68531961 5.66740773 5.62262803 5.66740773
 5.68233429 5.67337835 5.64949585 5.60770147 5.64352522 5.69129023
 5.61964272 5.60173084 5.6375546  5.62561335 5.68830492 5.64651054
 5.68531961 5.68830492 5.62262803 5.66740773 5.67039304 5.60173084
 5.62561335 5.72114336 5.63456928 5.68531961 5.59576021 5.61367209
 5.57784834 5.61964272 5.64053991 5.64651054 5.58978959 5.64949585
 5.63158397 5.62561335 5.63158397 5.6614371  5.66442242 5.71218742
 5.59576021 5.67337835 5.63158397 5.61964272 5.65845179 5.63158397
 5.69129023 5.61367209 5.65546648 5.67337835 5.67934898 5.63158397
 5.60471615 5.69129023 5.65845179 5.62859866 5.62859866 5.57486302
 5.58978959 5.68531961 5.77189369 5.69427555 5.7300993  5.65248116
 5.61068678 5.68830492 5.60471615 5.66740773 5.66740773 5.5688924
 5.76592306 5.62561335 5.6614371  5.56590708 5.64053991 5.61068678
 5.63158397 5.67039304 5.66442242 5.67934898 5.64949585 5.62561335
 5.61665741 5.67636367 5.56292177 5.60173084 5.61665741 5.66740773
 5.70920211 5.62262803 5.61068678 5.64949585 5.56292177 5.61068678
 5.64949585 5.62859866 5.75696712 5.60770147 5.62262803 5.60770147
 5.64352522 5.61665741 5.62262803 5.61665741 5.64949585 5.64352522
 5.64352522 5.68233429 5.68531961 5.62561335 5.68531961 5.61964272
 5.60770147 5.59874553 5.70920211 5.61964272 5.64352522 5.67934898
 5.60471615 5.6614371  5.67337835 5.7300993  5.52112739 5.62859866
 5.58978959 5.67337835 5.67039304 5.75398181 5.67039304 5.67039304
 5.67636367 5.68233429 5.61665741 5.62262803 5.57486302 5.64352522
 5.67636367 5.60770147 5.60770147 5.67636367 5.60770147 5.64352522
 5.5688924  5.65248116 5.73905524 5.72114336 5.62561335 5.75398181
 5.67636367 5.68830492 5.70323149 5.65546648 5.64352522 5.58083365]

In [77]:
model_diff = pd.DataFrame({'Actual value': y_test, 'Predicted value': y_pred_model})
model_diff.head()

      Actual value  Predicted value
1254             5         5.613672
1087             6         5.646511
822              5         5.550981
1514             6         5.574863
902              7         5.559936

In [78]:
#Model Evaluation
from sklearn import metrics
meanAbErr = metrics.mean_absolute_error(y_test, y_pred_model)
meanSqErr = metrics.mean_squared_error(y_test, y_pred_model)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(y_test, y_pred_model))
print('R squared: {:.2f}'.format(model.score(x,y)*100))
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

R squared: 0.33
Mean Absolute Error: 0.6767313071107409
Mean Square Error: 0.6366778181647331
Root Mean Square Error: 0.7979209347828474